version: '3.8'

x-base_service: &base_service
  volumes:
    - &v1 ./data:/data
    - &v2 ./output:/output
  stop_signal: SIGKILL
  tty: true
  devices:
    - nvidia.com/gpu=all

services:
  download:
    build: ./services/download/
    profiles: [ "download" ]
    volumes:
      - *v1

  auto:
    <<: *base_service
    profiles: [ "auto" ]
    build: ./services/AUTOMATIC1111
    environment:
      - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api
    ports:
      - "7860:7860"

  invoke:
    <<: *base_service
    profiles: [ "invoke" ]
    build: ./services/invoke/
    environment:
      - PRELOAD=true
      - CLI_ARGS=--xformers
    ports:
      - "7861:7861"

  comfy:
    <<: *base_service
    profiles: [ "comfy" ]
    build: ./services/comfy/
    environment:
      - CLI_ARGS=
    ports:
      - "7862:7862"
