# Created with podman-5.2.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-08-23T12:47:25Z"
  labels:
    app: stable-diffusion-webuis
  name: stable-diffusion-webuis
spec:
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /opt/stable-diffusion-webuis-podman/data
      type: Directory
    name: volume-data
  - hostPath:
      path: /opt/stable-diffusion-webuis-podman/output
      type: Directory
    name: volume-output
  initContainers:
  - image: localhost/container-download:latest
    name: container-download
    volumeMounts:
    - mountPath: /data
      name: volume-data
    tty: true
  containers:
  - args:
    - /bin/sh
    - -c
    - python -u webui.py --listen --port 7860 ${CLI_ARGS}
    image: localhost/container-automatic1111:latest
    name: container-automatic1111
    volumeMounts:
    - mountPath: /data
      name: volume-data
    - mountPath: /output
      name: volume-output
    ports:
    - containerPort: 7860
      hostPort: 7860
    env:
    - name: CLI_ARGS
      value: "--allow-code --medvram --xformers --enable-insecure-extension-access --api"
    tty: true
    resources:
      limits:
        nvidia.com/gpu: 1
  - args:
    - /bin/sh
    - -c
    - invokeai --web --host 0.0.0.0 --port 7861 --root_dir ${ROOT} --config ${CONFIG_DIR}/models.yaml     --outdir
      /output/invoke --embedding_directory /data/embeddings/ --lora_directory /data/models/Lora     --no-nsfw_checker
      --no-safety_checker ${CLI_ARGS}
    image: localhost/container-invoke:latest
    name: container-invoke
    volumeMounts:
    - mountPath: /data
      name: volume-data
    - mountPath: /output
      name: volume-output
    ports:
    - containerPort: 7861
      hostPort: 7861
    env:
    - name: CLI_ARGS
      value: "--xformers"
    - name: PRELOAD
      value: true
    tty: true
    resources:
      limits:
        nvidia.com/gpu: 1
  - args:
    - /bin/sh
    - -c
    - python -u main.py --listen --port 7862 ${CLI_ARGS}
    image: localhost/container-comfy:latest
    name: container-comfy
    volumeMounts:
    - mountPath: /output
      name: volume-output
    - mountPath: /data
      name: volume-data
    ports:
    - containerPort: 7862
      hostPort: 7862
    env:
    - name: CLI_ARGS
      value: ""
    tty: true
    resources:
      limits:
        nvidia.com/gpu: 1
