# Created with podman-5.2.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-08-23T12:47:25Z"
  labels:
    app: stable-diffusion-webuis
  name: stable-diffusion-webuis
spec:
  restartPolicy: Never
  volumes:
  - hostPath:
      path: /opt/stable-diffusion-webuis-podman/data
      type: Directory
    name: volume-data
  - hostPath:
      path: /opt/stable-diffusion-webuis-podman/output
      type: Directory
    name: volume-output
  initContainers:
  - image: localhost/container-download:latest
    name: container-download
    volumeMounts:
    - mountPath: /data
      name: volume-data
    tty: true
  containers:
  - image: localhost/container-automatic1111:latest
    args:
    - python3
    - -u
    - webui.py
    - --listen
    - --port
    - 7860
    - --allow-code
    - --medvram
    - --xformers
    - --enable-insecure-extension-access
    - --api
    name: container-automatic1111
    volumeMounts:
    - mountPath: /data
      name: volume-data
    - mountPath: /output
      name: volume-output
    ports:
    - containerPort: 7860
      hostPort: 7860
    tty: true
    resources:
      limits:
        nvidia.com/gpu: 1
  - image: localhost/container-invokeai:latest
    name: container-invokeai
    volumeMounts:
    - mountPath: /data
      name: volume-data
    - mountPath: /output
      name: volume-output
    ports:
    - containerPort: 7861
      hostPort: 7861
    env:
    - name: INVOKEAI_PORT
      value: 7861
    tty: true
    resources:
      limits:
        nvidia.com/gpu: 1
  - image: localhost/container-comfy:latest
    args:
    - python3
    - -u
    - main.py
    - --listen
    - --port
    - 7862
    name: container-comfy
    volumeMounts:
    - mountPath: /output
      name: volume-output
    - mountPath: /data
      name: volume-data
    ports:
    - containerPort: 7862
      hostPort: 7862
    tty: true
    resources:
      limits:
        nvidia.com/gpu: 1
